name: Terraform Lint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Terraform init
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'module'
    - name: Terraform fmt
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'module'
